name: Update README

on:
  schedule:
    - cron: "0 * * * *"   # every hour
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update stats in README
        run: |
          STARS=$(curl -s https://api.github.com/repos/Kunalray0707/Zomato-Sales-Performance | jq '.stargazers_count')
          FORKS=$(curl -s https://api.github.com/repos/Kunalray0707/Zomato-Sales-Performance | jq '.forks_count')
          DATE=$(date +"%d %b %Y %H:%M UTC")

          sed -i "s/⭐ Stars:.*/⭐ Stars: $STARS/" README.md
          sed -i "s/🍴 Forks:.*/🍴 Forks: $FORKS/" README.md
          sed -i "s/<!--LAST_UPDATED-->.*/$DATE/" README.md

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "🔄 Auto अपडेट: Stats & Timestamp" || echo "No changes"
          git push
